build_from:
  amd64: "lscr.io/linuxserver/obsidian:latest"
  arm64: "lscr.io/linuxserver/obsidian:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Obsidian Remote"
  org.opencontainers.image.description: "Allows to view and download files from Home Assistant backups"
  org.opencontainers.image.source: "https://github.com/alexbelgium/crazyrokr/tree/master/ha-obsidian-remote"
  org.opencontainers.image.licenses: "MIT license"
