name: Home Assistant Obsidian Remote
version: "0.3"
slug: ha-obsidian-remote
description: Runs Obsidian within your Home Assistant setup providing integration of live-features
url: https://github.com/crazyrokr/ha-obsidian-remote
webui: https://[HOST]:[PORT:3001]
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: False
    path: /config
  - type: data
    read_only: False
    path: /vaults
ingress: true
ingress_port: 3001
ports:
  3000/tcp: 3000
  3001/tcp: 3001
  8082/tcp: 8082
