name: Home Assistant Obsidian Remote
version: "0.14"
slug: ha-obsidian-remote
description: Runs Obsidian within your Home Assistant setup providing integration of live-features
url: https://github.com/crazyrokr/ha-obsidian-remote
webui: http://[HOST]:[PORT:3000]
arch:
  - aarch64
  - amd64
init: false
tmpfs: true
map:
  - type: data
    read_only: False
    path: /config
  # - type: share
  #   read_only: False
  #   path: /media
environment:
  PUID: "1000"
  PGID: "1000"
  PATH: "/sbin:/lsiopy/bin"
ingress: true
ingress_port: 3000
ports:
  3000/tcp: null
  3001/tcp: null
  8082/tcp: null
